# Generated by Django 4.0.1 on 2026-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('deposit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
