# Generated by Django 4.0.1 on 2026-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.IntegerField()),
                ('pname', models.CharField(max_length=70)),
                ('pquantity', models.IntegerField()),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
