# Generated by Django 4.0.1 on 2026-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=90)),
                ('author_name', models.CharField(max_length=90)),
                ('publisher', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('shelf_no', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
